# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Pedro H. Santos\Desktop\Olá San Diego\Projeto\ui\sandiego.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(255,165,0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_content = QtWidgets.QFrame(self.centralwidget)
        self.fr_content.setMinimumSize(QtCore.QSize(0, 35))
        self.fr_content.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fr_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_content.setObjectName("fr_content")
        self.fr_search = QtWidgets.QFrame(self.fr_content)
        self.fr_search.setGeometry(QtCore.QRect(150, 230, 500, 60))
        self.fr_search.setMinimumSize(QtCore.QSize(500, 0))
        self.fr_search.setMaximumSize(QtCore.QSize(600, 70))
        self.fr_search.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_search.setObjectName("fr_search")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_search)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ld_search = QtWidgets.QLineEdit(self.fr_search)
        self.ld_search.setMinimumSize(QtCore.QSize(0, 40))
        self.ld_search.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ld_search.setFont(font)
        self.ld_search.setStyleSheet("QLineEdit{\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: rgb(255,165,0);\n"
"    color: rgb(255,255,255);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(0, 122, 209);\n"
"    border: 2px solid rgb(172, 235, 226);\n"
"    border: 2px solid rgb(0, 139, 209);\n"
"    color: rgb(255,255,255);\n"
"}")
        self.ld_search.setObjectName("ld_search")
        self.horizontalLayout_3.addWidget(self.ld_search)
        self.btn_search = QtWidgets.QPushButton(self.fr_search)
        self.btn_search.setMinimumSize(QtCore.QSize(90, 32))
        self.btn_search.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_search.setFont(font)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(0,0,0);\n"
"    color: rgb(200,200,200);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255,255,255);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_3.addWidget(self.btn_search)
        self.label = QtWidgets.QLabel(self.fr_content)
        self.label.setGeometry(QtCore.QRect(230, 160, 341, 50))
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,255,255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.fr_content)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(350, 10, 141, 141))
        self.frame.setStyleSheet("background-image: url(:/logo/sandiego2.png);\n"
"background-repeat:  url(:/logo/turnordeste.png); \n"
"background-position: center;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(-30, 10, 561, 171))
        font = QtGui.QFont()
        font.setFamily("TeX Gyre Adventor")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,255,255);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Pedro H. Santos\\Desktop\\Olá San Diego\\Projeto\\ui\\sandiego2.png"))
        self.label_2.setObjectName("label_2")
        self.fr_result = QtWidgets.QFrame(self.fr_content)
        self.fr_result.setGeometry(QtCore.QRect(115, 300, 570, 190))
        self.fr_result.setMinimumSize(QtCore.QSize(540, 190))
        self.fr_result.setStyleSheet("border-radius: 5px;\n"
"padding: 5px;\n"
"background-color: rgb(255,165,0);\n"
"color: rgb(200,200,200);")
        self.fr_result.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_result.setObjectName("fr_result")
        self.lb_result = QtWidgets.QLabel(self.fr_result)
        self.lb_result.setGeometry(QtCore.QRect(17, 30, 535, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lb_result.setFont(font)
        self.lb_result.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lb_result.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_result.setObjectName("lb_result")
        self.btn_close = QtWidgets.QPushButton(self.fr_result)
        self.btn_close.setGeometry(QtCore.QRect(540, 10, 20, 20))
        self.btn_close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/close/close.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"        background-color: rgb(255,165,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35,35,35);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.fr_content)
        self.fr_top = QtWidgets.QFrame(self.centralwidget)
        self.fr_top.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_top.setObjectName("fr_top")
        self.verticalLayout.addWidget(self.fr_top)
        self.fr_button = QtWidgets.QFrame(self.centralwidget)
        self.fr_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.fr_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_button.setObjectName("fr_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_button)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_credits = QtWidgets.QLabel(self.fr_button)
        self.lb_credits.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-right: 5px;")
        self.lb_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_credits.setObjectName("lb_credits")
        self.horizontalLayout.addWidget(self.lb_credits)
        self.verticalLayout.addWidget(self.fr_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ld_search, self.btn_search)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Olá San Diego"))
        self.ld_search.setPlaceholderText(_translate("MainWindow", "Ex: distância entre o 1º e o 10º cruzamento."))
        self.btn_search.setText(_translate("MainWindow", "Procurar"))
        self.lb_result.setText(_translate("MainWindow", "<html><head/><body><p><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:8pt; color:#ffffff;\">R</span><span style=\" font-family:\'inherit\'; font-size:8pt; color:#ffffff;\">esultado da pesquisa</span></p><p><span style=\" font-family:\'inherit\'; font-size:8pt; color:#ffffff;\">Por favor, insira os números do cruzamento que você deseja pesquisar!</span></p></body></html>"))
        self.lb_credits.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"Cin.ufpe.br/~phfcs\"><span style=\" text-decoration: underline; color:#0000ff;\">Desenvolvido por Bruno Cezario e Pedro Santos.</span></a></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
